"""add channel to conversation_messages and slack_user_id to users

Revision ID: 772fc7c90f28
Revises: d705f154255e
Create Date: 2026-03-15 15:12:19.345762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772fc7c90f28'
down_revision: Union[str, Sequence[str], None] = 'd705f154255e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('channel', sa.String(length=20), server_default='cli', nullable=False))
    op.add_column('users', sa.Column('slack_user_id', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_column('users', 'slack_user_id')
    op.drop_column('conversation_messages', 'channel')
    # ### end Alembic commands ###
