"""add accountability coaching fields and growing plan items

Revision ID: d2813747f8c8
Revises: 772fc7c90f28
Create Date: 2026-03-15 16:39:57.913226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2813747f8c8'
down_revision: Union[str, Sequence[str], None] = '772fc7c90f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growing_plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plant_spec_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('optimal_sow_start', sa.Date(), nullable=True),
    sa.Column('optimal_sow_end', sa.Date(), nullable=True),
    sa.Column('suggested_alternative_id', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_spec_id'], ['plant_specs.id'], ),
    sa.ForeignKeyConstraint(['suggested_alternative_id'], ['plant_specs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growing_plan_items_plant_spec_id'), 'growing_plan_items', ['plant_spec_id'], unique=False)
    op.create_index(op.f('ix_growing_plan_items_user_id'), 'growing_plan_items', ['user_id'], unique=False)
    op.add_column('engagement_profiles', sa.Column('unanswered_count', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('engagement_profiles', sa.Column('current_frequency', sa.String(length=20), server_default='normal', nullable=False))
    op.add_column('plant_specs', sa.Column('growth_milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plant_specs', sa.Column('interesting_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plants', sa.Column('next_milestone_index', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('plants', sa.Column('next_milestone_date', sa.Date(), nullable=True))
    op.add_column('plants', sa.Column('milestone_delayed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'milestone_delayed')
    op.drop_column('plants', 'next_milestone_date')
    op.drop_column('plants', 'next_milestone_index')
    op.drop_column('plant_specs', 'interesting_facts')
    op.drop_column('plant_specs', 'growth_milestones')
    op.drop_column('engagement_profiles', 'current_frequency')
    op.drop_column('engagement_profiles', 'unanswered_count')
    op.drop_index(op.f('ix_growing_plan_items_user_id'), table_name='growing_plan_items')
    op.drop_index(op.f('ix_growing_plan_items_plant_spec_id'), table_name='growing_plan_items')
    op.drop_table('growing_plan_items')
    # ### end Alembic commands ###
