"""add growing_seasons, weather_logs, engagement_profiles tables and plant lineage fields

Revision ID: e4f9aa31db44
Revises: ec3a682f0ec0
Create Date: 2026-03-14 17:20:20.545928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f9aa31db44'
down_revision: Union[str, Sequence[str], None] = 'ec3a682f0ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('postcode_outward', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_max_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_max_kmh', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sunshine_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('frost', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postcode_outward', 'date', name='uq_weather_postcode_date')
    )
    op.create_index(op.f('ix_weather_logs_date'), 'weather_logs', ['date'], unique=False)
    op.create_index(op.f('ix_weather_logs_postcode_outward'), 'weather_logs', ['postcode_outward'], unique=False)
    op.create_table('engagement_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_time', sa.String(length=20), nullable=False),
    sa.Column('notification_level', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('last_sage_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_profiles_user_id'), 'engagement_profiles', ['user_id'], unique=True)
    op.create_table('growing_seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('season_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growing_seasons_user_id'), 'growing_seasons', ['user_id'], unique=False)
    op.create_index(op.f('ix_growing_seasons_year'), 'growing_seasons', ['year'], unique=False)
    op.add_column('context_events', sa.Column('weather_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plants', sa.Column('growing_season_id', sa.Uuid(), nullable=True))
    op.add_column('plants', sa.Column('parent_plant_id', sa.Uuid(), nullable=True))
    op.add_column('plants', sa.Column('seed_source', sa.String(length=30), nullable=True))
    op.add_column('plants', sa.Column('final_outcome', sa.String(length=20), nullable=True))
    op.add_column('plants', sa.Column('yield_total_kg', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('plants', sa.Column('season_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_plants_growing_season_id'), 'plants', ['growing_season_id'], unique=False)
    op.create_foreign_key(None, 'plants', 'growing_seasons', ['growing_season_id'], ['id'])
    op.create_foreign_key(None, 'plants', 'plants', ['parent_plant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_index(op.f('ix_plants_growing_season_id'), table_name='plants')
    op.drop_column('plants', 'season_notes')
    op.drop_column('plants', 'yield_total_kg')
    op.drop_column('plants', 'final_outcome')
    op.drop_column('plants', 'seed_source')
    op.drop_column('plants', 'parent_plant_id')
    op.drop_column('plants', 'growing_season_id')
    op.drop_column('context_events', 'weather_snapshot')
    op.drop_index(op.f('ix_growing_seasons_year'), table_name='growing_seasons')
    op.drop_index(op.f('ix_growing_seasons_user_id'), table_name='growing_seasons')
    op.drop_table('growing_seasons')
    op.drop_index(op.f('ix_engagement_profiles_user_id'), table_name='engagement_profiles')
    op.drop_table('engagement_profiles')
    op.drop_index(op.f('ix_weather_logs_postcode_outward'), table_name='weather_logs')
    op.drop_index(op.f('ix_weather_logs_date'), table_name='weather_logs')
    op.drop_table('weather_logs')
    # ### end Alembic commands ###
