"""initial schema

Revision ID: ec3a682f0ec0
Revises: 
Create Date: 2026-03-13 17:58:58.314738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec3a682f0ec0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('botanical_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('uk_hardiness', sa.String(length=20), nullable=True),
    sa.Column('growing_difficulty', sa.String(length=20), nullable=True),
    sa.Column('soil_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sun_requirements', sa.String(length=20), nullable=True),
    sa.Column('water_needs', sa.String(length=10), nullable=True),
    sa.Column('spacing_cm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('days_to_germination_min', sa.Integer(), nullable=True),
    sa.Column('days_to_germination_max', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest_min', sa.Integer(), nullable=True),
    sa.Column('days_to_harvest_max', sa.Integer(), nullable=True),
    sa.Column('common_pests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companion_plants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('antagonist_plants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('postcode_outward', sa.String(length=4), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('uk_region', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('subscription_tier', sa.String(length=10), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=50), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_type', sa.String(length=50), nullable=False),
    sa.Column('badge_tier', sa.String(length=10), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('gardens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('size_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('garden_type', sa.String(length=30), nullable=True),
    sa.Column('growing_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('microclimate_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('water_source', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gardens_user_id'), 'gardens', ['user_id'], unique=False)
    op.create_table('growing_calendar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_spec_id', sa.Uuid(), nullable=False),
    sa.Column('uk_region', sa.String(length=50), nullable=False),
    sa.Column('activity', sa.String(length=30), nullable=False),
    sa.Column('month_start', sa.SmallInteger(), nullable=False),
    sa.Column('month_end', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_spec_id'], ['plant_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growing_calendar_plant_spec_id'), 'growing_calendar', ['plant_spec_id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('plant_spec_id', sa.Uuid(), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('location_description', sa.String(length=200), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('planting_method', sa.String(length=30), nullable=True),
    sa.Column('growth_stage', sa.String(length=30), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('health_score', sa.SmallInteger(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('harvest_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_spec_id'], ['plant_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_garden_id'), 'plants', ['garden_id'], unique=False)
    op.create_index(op.f('ix_plants_plant_spec_id'), 'plants', ['plant_spec_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('user_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_agent', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('context_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('garden_id', sa.Uuid(), nullable=True),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_agent', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('related_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('outcome_tracked', sa.Boolean(), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_events_event_type'), 'context_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_context_events_user_id'), 'context_events', ['user_id'], unique=False)
    op.create_table('photo_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cv_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cv_model_version', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_media_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_records_plant_id'), 'photo_records', ['plant_id'], unique=False)
    op.create_index(op.f('ix_photo_records_user_id'), 'photo_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_records_user_id'), table_name='photo_records')
    op.drop_index(op.f('ix_photo_records_plant_id'), table_name='photo_records')
    op.drop_table('photo_records')
    op.drop_index(op.f('ix_context_events_user_id'), table_name='context_events')
    op.drop_index(op.f('ix_context_events_event_type'), table_name='context_events')
    op.drop_table('context_events')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_plants_plant_spec_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_garden_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_growing_calendar_plant_spec_id'), table_name='growing_calendar')
    op.drop_table('growing_calendar')
    op.drop_index(op.f('ix_gardens_user_id'), table_name='gardens')
    op.drop_table('gardens')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('plant_specs')
    # ### end Alembic commands ###
